import 'package:flutter/foundation.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_messaging/firebase_messaging.dart';
import 'package:votera_app/core/storage/secure_storage.dart';
import 'package:votera_app/features/notification/data/datasources/notification_remote_datasource.dart';
import 'package:votera_app/firebase_options.dart';
import 'package:package_info_plus/package_info_plus.dart';

/// Handles Firebase Messaging initialization and FCM device token management.
class PushNotificationService {
  PushNotificationService(this._secureStorage, this._remote, {this.vapidKey});

  final SecureStorageService _secureStorage;
  final NotificationRemoteDataSource _remote;
  final String? vapidKey;

  /// Initialize Firebase (if needed), request permissions and fetch token.
  Future<void> init() async {
    try {
      // Initialize Firebase if not already initialized. On web, the app
      // must be configured with FirebaseOptions (generated by flutterfire).
      if (kIsWeb) {
        // Initialize Dart-side Firebase on web with explicit options so that
        // firebase_* web packages have a valid default app to use.
        if (Firebase.apps.isEmpty) {
          await Firebase.initializeApp(options: DefaultFirebaseOptions.web);
        }
      } else {
        if (Firebase.apps.isEmpty) await Firebase.initializeApp();
      }

      // Request permissions on iOS / macOS.
      if (!kIsWeb) {
        final settings = await FirebaseMessaging.instance.requestPermission(
          alert: true,
          announcement: false,
          badge: true,
          carPlay: false,
          criticalAlert: false,
          provisional: false,
          sound: true,
        );
        if (settings.authorizationStatus == AuthorizationStatus.denied) {
          // Permission denied — do not attempt to get token.
          return;
        }
      }

      // Web flow: request permission, then get token with VAPID key and register it.
      if (kIsWeb) {
        try {
          final settings = await FirebaseMessaging.instance.requestPermission();
          if (kDebugMode) {
            // ignore: avoid_print
            print('FCM web permission: ${settings.authorizationStatus}');
          }
          if (settings.authorizationStatus == AuthorizationStatus.denied) {
            if (kDebugMode) {
              // ignore: avoid_print
              print(
                'Notification permission denied on web; token will not be generated',
              );
            }
            return;
          }
        } catch (e) {
          if (kDebugMode) {
            // ignore: avoid_print
            print('FCM requestPermission error (web): $e');
          }
        }

        try {
          final token = await FirebaseMessaging.instance.getToken(
            vapidKey: vapidKey,
          );
          if (token != null && token.isNotEmpty) {
            if (kDebugMode) {
              // ignore: avoid_print
              print('FCM token (web): $token');
            }
            await _secureStorage.setFcmToken(token);
            try {
              final appVersion = await _getAppVersion();
              await _remote.registerDeviceToken(
                token: token,
                deviceTypeId: _detectDeviceType(),
                deviceName: _deviceName(),
                appVersion: appVersion,
              );
            } catch (e) {
              if (kDebugMode) {
                // ignore: avoid_print
                print('Failed to register token with backend (web): $e');
              }
            }

            FirebaseMessaging.instance.onTokenRefresh.listen((newToken) async {
              await _secureStorage.setFcmToken(newToken);
              try {
                final appVersion = await _getAppVersion();
                await _remote.registerDeviceToken(
                  token: newToken,
                  deviceTypeId: _detectDeviceType(),
                  deviceName: _deviceName(),
                  appVersion: appVersion,
                );
              } catch (e) {
                if (kDebugMode) {
                  // ignore: avoid_print
                  print(
                    'Failed to register refreshed token with backend (web): $e',
                  );
                }
              }
            });
          } else {
            if (kDebugMode) {
              // ignore: avoid_print
              print('FCM.getToken returned null or empty on web');
            }
          }
        } catch (e) {
          if (kDebugMode) {
            // ignore: avoid_print
            print('Error fetching FCM token on web: $e');
          }
        }

        return;
      }

      // Non-web platforms: get token and register it.
      try {
        final token = await FirebaseMessaging.instance.getToken();
        if (token != null && token.isNotEmpty) {
          if (kDebugMode) {
            // ignore: avoid_print
            print('FCM token: $token');
          }
          await _secureStorage.setFcmToken(token);
          try {
            final appVersion = await _getAppVersion();
            await _remote.registerDeviceToken(
              token: token,
              deviceTypeId: _detectDeviceType(),
              deviceName: _deviceName(),
              appVersion: appVersion,
            );
          } catch (e) {
            if (kDebugMode) {
              // ignore: avoid_print
              print('Failed to register token with backend: $e');
            }
          }

          FirebaseMessaging.instance.onTokenRefresh.listen((newToken) async {
            await _secureStorage.setFcmToken(newToken);
            try {
              final appVersion = await _getAppVersion();
              await _remote.registerDeviceToken(
                token: newToken,
                deviceTypeId: _detectDeviceType(),
                deviceName: _deviceName(),
                appVersion: appVersion,
              );
            } catch (e) {
              if (kDebugMode) {
                // ignore: avoid_print
                print('Failed to register refreshed token with backend: $e');
              }
            }
          });
        } else {
          if (kDebugMode) {
            // ignore: avoid_print
            print('FCM.getToken returned null or empty on native');
          }
        }
      } catch (e) {
        if (kDebugMode) {
          // ignore: avoid_print
          print('Error fetching FCM token on native platforms: $e');
        }
      }
    } catch (e) {
      // Avoid crashing app if FCM init fails. Caller can check storage.
      if (kDebugMode) {
        // ignore: avoid_print
        print('PushNotificationService.init error: $e');
      }
    }
  }

  Future<String?> getSavedToken() => _secureStorage.getFcmToken();

  /// If an auth access token exists, sends any saved FCM token to backend.
  Future<void> sendSavedTokenIfAuth() async {
    try {
      final access = await _secureStorage.getAccessToken();
      if (access == null || access.isEmpty) return;
      final token = await _secureStorage.getFcmToken();
      if (token == null || token.isEmpty) return;
      final appVersion = await _getAppVersion();
      await _remote.registerDeviceToken(
        token: token,
        deviceTypeId: _detectDeviceType(),
        deviceName: _deviceName(),
        appVersion: appVersion,
      );
    } catch (e) {
      if (kDebugMode) {
        // ignore: avoid_print
        print('sendSavedTokenIfAuth error: $e');
      }
    }
  }

  Future<String> _getAppVersion() async {
    if (kIsWeb) return '';
    try {
      final info = await PackageInfo.fromPlatform();
      return info.version;
    } catch (_) {
      return '';
    }
  }

  int _detectDeviceType() {
    // DeviceTypeId mapping (example): 1=Android,2=iOS,3=Web
    if (kIsWeb) return 3;
    // There's no direct Platform import to avoid bringing dart:io on web.
    // Use default: 1 (Android) — caller can adjust if needed.
    return 1;
  }

  String _deviceName() {
    // Return a simple device name placeholder. Could be improved with device_info_plus.
    return kIsWeb ? 'web' : 'device';
  }
}
